---
- name: Install dependencies for rbenv
  apt: pkg=git
  tags: rbenv

- name: Check if rbenv is installed
  shell: "ls -la | grep .rbenv"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: Install rbenv
  sudo: yes
  sudo_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv version={{ rbenv_version }}
  when: rbenv_check_install|failed
  tags: rbenv

- name: Add ~.rbenv/bin to PATH
  command: echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> ~/.bashrc
  when: rbenv_check_install|failed
  tags: rbenv

- name: Eval rbenv init in ~/.profile
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'
  when: rbenv_check_install|failed
  tags: rbenv

- name: Launch profile
  command: "exec $SHELL"
  when: rbenv_check_install|failed

- name: Install dependencies for ruby-build
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev
  tags: rbenv

- name: Check if ruby-build is installed
  shell: "ls -la ~/.rbenv/plugins | grep ruby-build"
  register: ruby_build_check_install
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: Install ruby-build as rbenv plugin
  sudo: yes
  sudo_user: "{{ rbenv_user }}"
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  when: ruby_build_check_install|failed
  tags: rbenv

# TODO: Need to be fixed because ansible doesn't find rbenv whetever its really exist
# in the session or not
- name: "Check if {{ ruby_version_rbenv }} is installed"
  shell: "rbenv versions | grep {{ ruby_version_rbenv }}"
  register: ruby_check_install
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: "Install {{ ruby_version_rbenv }}"
  command: "rbenv install {{ ruby_version_rbenv }}"
  when: ruby_check_install|failed
  ignore_errors: True
  tags: rbenv

- name: "Check if {{ ruby_version_rbenv }} is the default ruby version"
  shell: "rbenv version | grep {{ ruby_version_rbenv }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: True
  tags: rbenv

- name: "Remove this useless gemrc file"
  sudo: yes
  command: rm -rf /home/{{ user }}/.gemrc
  tags: bundler

- name: "Set up bundler "
  command: "chdir=/home/{{ rbenv_user }}/ gem install bundler"
  tags: bundler
  ignore_errors: True

# # THis one is little bit special since the version 2.0.0-p195 doesn't work very well with a simple rbenv install
# - name: "Set the good version of ruby"
#   command: 'curl -fsSL https://gist.github.com/LeonB/10503374/raw | rbenv install --patch 2.0.0-p195'
#   tags: set up 2.0.0-p195
#   ignore_errors: True